# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_auto_20190723_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='otrip',
            field=models.ManyToManyField(related_name='trips', to='login_app.Otrip'),
        ),
    ]
