# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_trip_otrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otrip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='otrip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='otrip',
            field=models.ManyToManyField(related_name='user_otrip', to='login_app.Trip'),
        ),
        migrations.AddField(
            model_name='user',
            name='trip',
            field=models.ManyToManyField(related_name='user_trip', to='login_app.Trip'),
        ),
    ]
